trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  azureServiceConnection: 'sc-to-azure'

steps:

# ==========================================
# 1. Install Terraform
# ==========================================
- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: 'latest'


# ==========================================
# 2. Terraform Init
# ==========================================
- script: |
    terraform init
  displayName: 'Terraform Init'


# ==========================================
# 3. Terraform Validate
# ==========================================
- script: |
    terraform validate
  displayName: 'Terraform Validate'


# ==========================================
# 4. Terraform Plan
# ==========================================
- task: AzureCLI@2
  displayName: 'Terraform Plan'
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform plan


# ==========================================
# 5. Terraform Apply
# ==========================================
- task: AzureCLI@2
  displayName: 'Terraform Apply'
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform apply -auto-approve